const quizData = [
  {
    id: 1,
    question: "Rita suffers from constant headaches and high blood pressure. Her residence is close to an airport. What could be the most likely cause of her condition?",
    options: {
      a: "Noise pollution",
      b: "Air pollution",
      c: "Nuclear pollution",
      d: "Water pollution",
    },
    answer: "a",
  },
  {
    id: 2,
    question: "An exo-endocrine gland in the human body is:",
    options: {
      a: "Pituitary gland",
      b: "Pancreas",
      c: "Salivary gland",
      d: "Adrenal gland",
    },
    answer: "b",
  },
  {
    id: 3,
    question: "Assertion: If both kidneys fail, urea from the blood is removed by dialysis.\nReason: Accumulation of urea in the human body is toxic.",
    options: {
      a: "A is True, and R is false.",
      b: "A is False, and R is true.",
      c: "Both A and R are true.",
      d: "Both A and R are false.",
    },
    answer: "c",
  },
  {
    id: 4,
    question: "Rajesh was told to buy a blue cloth by his craft teacher. He couldn't differentiate blue colour from green and hence brought a green cloth to class. Which medical reason could have resulted in this?",
    options: {
      a: "Myopia",
      b: "Cataract",
      c: "Colour blindness",
      d: "Hyperopia",
    },
    answer: "c",
  },
  {
    id: 5,
    question: "Mary sprinkled 5 kg of common salt on the grass growing on her lawn. After a couple of days, she observed that the grass had wilted and died. This was due to which of the following conditions?",
    options: {
      a: "Endosmosis",
      b: "Turgidity",
      c: "Deplasmolysis",
      d: "Plasmolysis",
    },
    answer: "d",
  },
  {
    id: 6,
    question: "In cholera, patients suffer from vomiting and watery bowels. They may die due to the:",
    options: {
      a: "poisoning by the accumulation of high quantities of urea in the body.",
      b: "ability of the intestines to absorb water into the blood.",
      c: "excretion of almost all the water by the kidneys.",
      d: "the failure of the kidneys.",
    },
    answer: "a",
  },
  {
    id: 7,
    question: "The given figures A and B show ______ and ______ stages of cell division.",
    options: {
      a: "prophase, metaphase",
      b: "telophase, anaphase",
      c: "metaphase, anaphase",
      d: "anaphase, telophase",
    },
    answer: "c",
  },
  {
    id: 8,
    question: "A person is suffering from kidney failure. He is put on a dialysis machine by the doctors. The osmotic pressure of dialysis fluid should be:",
    options: {
      a: "equal to that of blood.",
      b: "more than that of blood.",
      c: "less than that of blood.",
      d: "equal to zero.",
    },
    answer: "a",
  },
  {
    id: 9,
    question: "A squirrel is in a scary situation. The secreted adrenaline prepares the body to meet the situation. Which of the following is NOT TRUE for this situation?",
    options: {
      a: "Adrenaline prepares the body to fight danger.",
      b: "Extra energy and strength are provided to the body.",
      c: "At the time of the stress, fewer hormones are released into the blood.",
      d: "Adrenaline prepares the body to run away from danger.",
    },
    answer: "c",
  },
  {
    id: 10,
    question: "Assertion (A): The main pulmonary artery pumps oxygenated blood from the right vertical into the lungs.\nReason (R): Inside the lungs, the artery divides and divides several times to form capillaries around the air sacs.",
    options: {
      a: "A is True, and R is false.",
      b: "A is False, and R is true.",
      c: "Both A and R are true.",
      d: "Both A and R are false.",
    },
    answer: "b",
  },
  {
    id: 11,
    question: "Given below are some common reflexes in humans.\ni. Quick closing of the eyelids when a strong beam of light is flashed across.\nii. Apply brakes to your vehicle if anything suddenly comes in front.\niii. Playing a musical instrument\niv. Coughing reflex, when the food is swallowed, enters the windpipe.\nThe conditioned reflexes are:",
    options: {
      a: "i and ii",
      b: "ii and iii",
      c: "iii and iv",
      d: "i and iv",
    },
    answer: "b",
  },
  {
    id: 12,
    question: "Electrons released on splitting of water molecules in photosynthesis are used in producing:",
    options: {
      a: "NADP",
      b: "NADPH",
      c: "ATP",
      d: "O2",
    },
    answer: "c",
  },
  {
    id: 13,
    question: "The four major steps in seeing an object are:\ni. interpretation by the brain.\nii. focussing of image.\niii. entry of light rays.\niv. transmission of nerve impulses from the retina & brain.\nThe correct sequence will be:",
    options: {
      a: "i, ii, iii, iv",
      b: "ii, iii, iv, i",
      c: "iii, ii, iv, i",
      d: "iv, i, ii, iii",
    },
    answer: "c",
  },
  {
    id: 14,
    question: "Based on the given figure, identify the structural as well as the functional unit of kidney:",
    options: {
      a: "A",
      b: "B",
      c: "C",
      d: "D",
    },
    answer: "c",
  },
  {
    id: 15,
    question: "Assertion: Seminiferous tubules produce sperms.\nReason: Seminiferous tubules secrete Oxytocin, which aids in the production of sperm.",
    options: {
      a: "A is True, and R is false.",
      b: "A is False, and R is true.",
      c: "Both A and R are true.",
      d: "Both A and R are false.",
    },
    answer: "a",
  },
  {
    id: 16,
    question: "Assertion: The nerve impulse travels from the axon of a neuron to the axon of another neuron.\nReason: The end portion of the axon has swollen ends, which store neurotransmitters.",
    options: {
      a: "A is True, and R is false.",
      b: "A is False, and R is true.",
      c: "Both A and R are true.",
      d: "Both A and R are false.",
    },
    answer: "b",
  },
  {
    id: 17,
    question: "Thomas played cricket on a hot summer afternoon. His urine output was much less, though he drank plenty of water.\nWhat could be the possible cause?\nP - Kidneys reabsorb a lot of water\nQ - Sweat glands are active\nR - Kidneys absorb less water\nS - Sweat glands are inactive",
    options: {
      a: "R and Q",
      b: "P and Q",
      c: "P and S",
      d: "R and S",
    },
    answer: "b",
  },
  {
    id: 18,
    question: "Acid rain is caused due to polluted gases like Co2, So2, and oxides of nitrogen. The pollution which does not take place immediately after acid rain is:",
    options: {
      a: "Air pollution",
      b: "Water pollution",
      c: "Soil Pollution",
      d: "Noise Pollution",
    },
    answer: "a",
  },
  {
    id: 19,
    question: "Surya's father was diagnosed with Diabetes mellitus. The doctor advised him to avoid certain foods. Which are the foods he should avoid eating?\nP - Sweets\nQ - Leafy vegetables\nR - Bananas\nS - Pulses",
    options: {
      a: "P and R",
      b: "Q and S",
      c: "R and S",
      d: "P and Q",
    },
    answer: "a",
  },
  {
    id: 20,
    question: "During light adaptation:",
    options: {
      a: "Rods and cones become active.",
      b: "Rods and cones become inactive.",
      c: "Rods become active and cones inactive.",
      d: "Cones become active and rods inactive.",
    },
    answer: "d",
  },
  {
    id: 21,
    question: "A cell of a leaf of an aquatic plant is kept in a 5% salt solution for some time. The phenomenon which will take place is/are:",
    options: {
      a: "turgidity",
      b: "plasmolysis",
      c: "turgidity and flaccidity",
      d: "plasmolysis and flaccidity",
    },
    answer: "d",
  },
  {
    id: 22,
    type: "subjective",
    question: "Osmosis is controlled by the concentration of ______ molecules.",
    answer: "water",
  },
  {
    id: 23,
    type: "subjective",
    question: "An animal cell is kept in a lower solute concentration fluid. The cell will ______ (Enlarge/Shrink)",
    answer: "enlarge",
  },
  {
    id: 24,
    type: "subjective",
    question: "Plants absorb water from the roots because the cell sap is ______ concentrated than the surrounding fluids. (more, less)",
    answer: "more",
  },
  {
    id: 25,
    type: "subjective",
    question: "Human red blood cells, when kept in a hypertonic solution, ______ occurs. (Osmosis, endosmosis, exosmosis)",
    answer: "exosmosis",
  },
  {
    id: 26,
    type: "subjective",
    question: "Given below is an experimental setup. Concentrated sugar solution is taken in the thistle funnel. The mouth of the thistle funnel is covered with cellophane paper. The thistle funnel is inverted in a beaker containing water.\nThe above experiment demonstrates ______",
    answer: "osmosis",
  },
  {
    id: 27,
    type: "subjective",
    question: "After a few hours, the level of the sugar solution ______ in the thistle funnel.",
    answer: "rises/increases",
  },
  {
    id: 28,
    type: "subjective",
    question: "It allows only ______ molecules to pass through it freely.",
    answer: "water",
  },
  {
    id: 29,
    type: "subjective",
    question: "It prevents the passage of ______ molecules.",
    answer: "Sugar",
  },
  {
    id: 30,
    type: "subjective",
    question: "A control experiment can be set up by taking plain ______ in the thistle funnel and placing it in another beaker containing water.",
    answer: "water",
  },
  {
    id: 31,
    type: "subjective",
    question: "Haemorrhage frequently happens in viral dengue fever. Compare this condition with haemophilia.",
    answer: "In viral dengue fever, the number of platelets falls to a very low count, and coagulation occurs, leading to haemorrhage.\nWhile haemophilia is a genetic disorder in which blood does not clot properly.",
  },
  {
    id: 32,
    type: "subjective",
    question: "Differentiate in the rate of photosynthesis for the increase in temperature.\n(a) 20°to 30°C\n(b) 40°C to 50°C",
    answer: "(a) The rate of photosynthesis gets doubled.\n(b) Photosynthesis stops.",
  },
  {
    id: 33,
    type: "subjective",
    question: "Name the nitrogenous base with which Guanine pairs up in the helical structure of DNA and through how many hydrogen bonds?",
    answer: "Cytosine, 3 H-bonds",
  },
  {
    id: 34,
    type: "subjective",
    question: "When an irritant enters the nose, a sneezing reflex happens. Identify the stimulus and the response.",
    answer: "Stimulus – Irritant\nResponse – Sneezing",
  },
  {
    id: 35,
    type: "subjective",
    question: "An atomic explosion in 1945 in Japan led to a large number of persisting deformities in the bodies of plants and animals. What might have happened?",
    answer: "The mutation alters the hereditary material of an organism’s cells.",
  },
  {
    id: 36,
    type: "subjective",
    question: "Why is a bicuspid valve in the human heart named so?",
    answer: "It has two flaps.",
  },
  {
    id: 37,
    type: "subjective",
    question: "Under which condition does a leaf take carbon dioxide from the atmosphere?",
    answer: "When the concentration of Co2 is higher outside the leaf than inside.",
  },
  {
    id: 38,
    type: "subjective",
    question: "A pregnant lady is suffering from viral fever. Will the foetus be infected?",
    answer: "No, the placenta does not allow the passage of germs from the mother to the foetus.",
  },
  {
    id: 39,
    type: "subjective",
    question: "Why the blood flows through the glomerulus under great pressure?",
    answer: "The efferent (outgoing) arteriole is narrower than the afferent (incoming) arteriole. So, pressure increases.",
  },
  {
    id: 40,
    type: "subjective",
    question: "Differentiate between genotype and phenotype.",
    answer: "Genotype is the combination of genes, and phenotype is the expressed character.",
  },
  {
    id: 41,
    type: "subjective",
    question: "The number of asthma patients increases during winters in metropolitan cities like Delhi. Why is it so? How can it be reduced?",
    answer: "Smog (smoke + fog) leads to asthma. Air pollution causes respiratory problems.\nInstallation of tall chimneys in factories with filters, electrostatic precipitators.",
  },
  {
    id: 42,
    type: "subjective",
    question: "In our country, the infant mortality rate is high, but the population is still increasing in India. Explain.",
    answer: "People from the economically weaker sections think if safer to produce more children so that at least some may survive.",
  },
  {
    id: 43,
    type: "subjective",
    question: "Justify the statement – “Vermiform appendix is a vestigial organ in humans.”",
    answer: "The vermiform appendix projects from the blind end of the caecum and is a functionless (vestigial) organ in humans.",
  },
  {
    id: 44,
    type: "subjective",
    question: "What is Adrenal Virilism?",
    answer: "Overgrowth of the adrenal cortex in a mature woman results in the development of a beard, moustache and deep voice.",
  },
  {
    id: 45,
    type: "subjective",
    question: "Explain the function of corpus luteum when:\n(a) ovum is fertilised.\n(b) ovum is not fertilised.",
    answer: "(a) Corpus luteum releases progesterone and keeps the uterus in a state suitable for implantation.\n(b) The Corpus luteum stops producing progesterone.",
  },
  {
    id: 46,
    type: "subjective",
    question: "Shruti’s mother gave birth to two male babies. Both the babies had a strong resemblance to each other. The doctor said that they have been formed from a single ovum.\n(a) What kind of twins are they?\n(b) Why are they of the same gender?",
    answer: "(a) Identical twins\n(b) Since they develop from a single ovum, the gender of the twins is determined at the time of fertilisation.",
  },
  {
    id: 47,
    type: "subjective",
    question: "State the effect of Adrenaline on:\n(a) Pupils of eyes\n(b) Heartbeat",
    answer: "(a) Pupils dilate\n(b) Heartbeat increases",
  },
  {
    id: 48,
    type: "subjective",
    question: "When is albumin passed out in urine? Name this condition.",
    answer: "Due to high blood pressure, or due to increased permeability of the bowman’s capsule membrane on account of bacterial infection, albumin may be passed out via urine.\nAlbuminuria",
  },
  {
    id: 49,
    type: "subjective",
    question: "Mention the significance of the Testes being located inside the scrotum.",
    answer: "To maintain a temperature of 2-3°C less than body temperature for sperms to mature.\nProtect testes from injuries",
  },
  {
    id: 50,
    type: "subjective",
    question: "Give two examples of natural resources which cannot keep pace with the rising population.",
    answer: "Food, Water",
  },
  {
    id: 51,
    type: "subjective",
    question: "Keshav enters a dark room from a brightly lit area. He experiences difficulty in viewing objects, but gradually his vision improves. Explain the role of the photoreceptors in this case.",
    answer: "Rhodopsin gets bleached in bright light. It takes a few seconds for it to regenerate in dim light. Then, the vision improves.\nIodopsin does not function in dim light.",
  },
  {
    id: 52,
    type: "subjective",
    question: "On a winter night, a group of workers slept in a closed room, having a burning furnace to keep themselves warm. Most of them died in their sleep. What is the reason for their fatality?",
    answer: "Burning furnace emits CO. This combines with oxygen to form a stable compound, Carboxyhaemoglobin, which cuts off the supply of oxygen to tissues.",
  },
  {
    id: 53,
    type: "subjective",
    question: "Rohit’s father has increased thirst and hunger with frequent urination. He also gets fatigued very often. His doctor advised him to get a blood sugar profile test done.\n(a) Name the disease based on the symptoms given above.\n(b) Which is the hormone whose deficiency causes this disorder?\n(c) What is the technical term for high blood sugar level?",
    answer: "(a) Diabetes mellitus\n(b) Insulin\n(c) Hyperglycemia",
  },
  {
    id: 54,
    type: "subjective",
    question: "Farhan’s classroom is very close to the compound wall of his school. He was observing two pigeons sitting on the wall. He could see one bird clearly, but the image of the second bird was blurred as the pigeon was a little away from the first.\n(a) Name the defect of the eye Farhan is suffering from.\n(b) Where is the image of the second pigeon formed in his eyeballs?\n(c) What lens can be used to correct the defect?",
    answer: "(a) Myopia\n(b) Behind the retina\n(c) Concave",
  },
  {
    id: 55,
    type: "subjective",
    question: "Manoj was writing a composition on “The importance of Education in life”.\n(a) Name the part of the brain that Manoj uses for writing the composition.\n(b) Is it a voluntary or involuntary action?\n(c) Trace the nervous pathway using the following terms:\nMuscles of the hand, Sensory nerves, Fingertips, Motor nerves, and Brain.",
    answer: "(a) Cerebrum\n(b) Voluntary\n(c) Fingertips, Sensory nerves, Brain, Motor nerves, Muscles of hand",
  },
  {
    id: 56,
    type: "subjective",
    question: "Study the diagram given below and answer the questions that follow:\n(a) Identify the apparatus.\n(b) What is it used to measure?\n(c) Mention any one limitation of using the apparatus.",
    answer: "(a) Ganong’s Potometer\n(b) To measure the water uptake by the cut shoot\n(c) Difficult to introduce an air bubble",
  },
  {
    id: 57,
    type: "subjective",
    question: "The statements given below are false. Correct and rewrite the complete statements:\n(a) Fruit ripening is induced by Abscisic acid.\n(b) Roots show negative Hydrotropism.\n(c) Thigmotropism can be demonstrated by using a Clinostat.",
    answer: "(a) Fruit ripening is induced by Ethylene/ Senescence and falling of leaves is induced by Abscisic acid.\n(b) Shoots show negative Hydrotropism, / Roots show negative Phototropism.\n(c) Geotropism can be demonstrated by using a Clinostat.",
  },
  {
    id: 58,
    type: "subjective",
    question: "Two heterozygous pea plants having round seeds (Rr) are crossed with each other.\n(a) Write the Phenotypic ratio of the offspring.\n(b) What will the genotypic ratio of the offspring be?\n(c) Which of the above two traits is recessive?",
    answer: "(a) 3 : 1\n(b) 1 : 2 : 1\n(c) Wrinkled seeds",
  },
  {
    id: 59,
    type: "subjective",
    question: "How is the rate of transpiration affected under the following environmental conditions:\n(a) High temperature\n(b) Low humidity\n(c) Low intensity of sunlight",
    answer: "(a) More Transpiration\n(b) More Transpiration\n(c) Less Transpiration",
  }
];